---
title: 'ETC3250 Business Analytics: Classification'
author: "Souhaib Ben Taieb, Di Cook, Rob Hyndman"
date: "March 16, 2015"
output:
  ioslides_presentation:
    css: styles.css
    mathjax: local
    self_contained: no
    widescreen: yes
  beamer_presentation: default
---

## What is classification?

- Supervised classification includes multivariate techniques finding a rule for separating observations/cases into known classes, and using this rule to classify new observations.
- The process starts with a training sample, that is the full data set with known classes. Typically the variables that will be used to generate the classification rule are easy/cheap to measure, but the class is more difficult to measure. It is important to be able to classify new observations using variables that are easy to measure.

## Supervised vs Unsupervised

Unsupervised classification, also called cluster analysis, differs from supervised in that the classes are not known ahead of time, and need to be discovered first and labelled. 

## The simplest method 

- Calculate the mean of each class
- Calculate the distance between the new observation and each of the means
- Predict the new observation into the class of the closest mean

This is called *linear discriminant analysis* or *Fisher's linear discriminant*.

## Linear discriminant analysis

<div class="columns-2">

```{r crabs, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(ggplot2)
library(tourr)
data(flea)
library(dplyr)
fl.m <- summarise(group_by(flea, species), tars1=mean(tars1))
qplot(tars1, data=subset(flea, species != "Concinna "), geom="histogram",
      fill=species, binwidth=10, alpha=I(0.5)) + 
  geom_vline(data=subset(fl.m, species !="Concinna "), 
             aes(xintercept=tars1, color=species), size=1) + 
  geom_vline(xintercept=169.6, color="black")
```

- Example data: Species of beetles. Subset of two species. One of the six variables shown, where there is a difference between the two classes. 

- Everything to the right of the black line is classified to red (Heikert.) and to the left is blue (Heptapot.)
</div>

## Notes to self

- Give terminology
- Add creative commons license