---
title: "ETC3250 Lab 7"
author: "Di Cook"
date: "8 September 2015"
output: pdf_document
---


# Making data plots and cleaning data

# Assignment 7

On the PISA data from last week. Make a plot to answer this question:

- Does truancy affect math score, on average?

- And pick one other interesting question based on the data dictionary description information to answer using a plot. 

Write a couple of sentence explaining why you chose the particular plot design, 
and how it helps to answer the question.

Turn in two items: a .Rmd document, and the output .pdf from running it. No need to include the R output and plots in your pdf, but the code should be in the Rmd file. 

For truancy:

Below you have the means and standard deviations of math scores against frequency of skipping school. Skipping school decreases the score on average by almost 100 points once students skip school 5 or more times per month. There is a lot of variability, though, so some students who  skip school 5 or more times per month still do better than some students who never skip school.

```{r, echo=FALSE, message=FALSE, fig.width=4, fig.height=4}
library(dplyr)
library(ggplot2)
oz <- read.csv("../data/PISA-oz.csv") # You might need to change the directory to where the data is located on your computer
dim(oz)
oz.sub <- filter(oz, !is.na(ST09Q01))
oz.sub$truancy <- factor(oz.sub$ST09Q01, levels=c("None  ", "One or two times  ", "Three or four times  ", "Five or more times  "), labels=0:3)
truancy <- summarise(group_by(oz.sub, truancy), m = mean(PV1MATH),  s = sd(PV1MATH))
truancy
truancy$truancy <- as.numeric(as.character(truancy$truancy))
qplot(truancy, m, data=truancy, geom=c("point", "line")) + 
  geom_linerange(aes(ymin=m-s, ymax=m+s)) + ylim(c(0,1000)) + 
  ylab("Math score") + theme_bw()
```